name: numpy_indexed
channels:
  - anaconda
  - clinicalgraphics
  - BjornFJohansson
dependencies:
  - python
  - numpy
  - future
  # dev
  - pyyaml =3.11*
  - invoke >=0.11.1,<0.12
  - pypandoc
  # tests
  - pytest >=2.8.4,<2.9
